name: license_master
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  get: ^4.6.6
  flutter_staggered_grid_view: ^0.7.0
  google_fonts: ^5.0.0
  carousel_slider: ^4.2.1
  cached_network_image: ^3.3.1
  translator: ^1.0.0
  firebase_core: ^2.31.0
  cloud_firestore: ^4.17.3
  loading_animation_widget: ^1.2.1
  get_storage: ^2.1.1
  lottie: ^3.1.2
  firebase_auth: ^4.20.0
  url_launcher: ^6.0.20
  file_picker: ^8.0.5
  excel: ^4.0.3
  flutter_svg: ^2.0.10+1
  permission_handler: ^11.3.1
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.9.2

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/app_logo.png"
flutter:

  uses-material-design: true

  assets:
     - assets/images/
     - assets/lottie/
