// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB7ryYTN0QB3DBxLRkO4WcgyZ5l8qiYaKM',
    appId: '1:173490396619:web:6792307832e0deb6c7aa4e',
    messagingSenderId: '173490396619',
    projectId: 'kerala-psc-papers',
    authDomain: 'kerala-psc-papers.firebaseapp.com',
    databaseURL: 'https://kerala-psc-papers.firebaseio.com',
    storageBucket: 'kerala-psc-papers.appspot.com',
    measurementId: 'G-P7WEKEVZLB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCJJvmdm5pvtOGsfLpqOoKmUzXfLm_fLwM',
    appId: '1:173490396619:android:a8acd3b548912098c7aa4e',
    messagingSenderId: '173490396619',
    projectId: 'kerala-psc-papers',
    databaseURL: 'https://kerala-psc-papers.firebaseio.com',
    storageBucket: 'kerala-psc-papers.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDU-BWm1Q7r6kGKZUQ2G7rkY1hQdkQqWzE',
    appId: '1:173490396619:ios:7080c1789185b413c7aa4e',
    messagingSenderId: '173490396619',
    projectId: 'kerala-psc-papers',
    databaseURL: 'https://kerala-psc-papers.firebaseio.com',
    storageBucket: 'kerala-psc-papers.appspot.com',
    iosBundleId: 'com.example.licenceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDU-BWm1Q7r6kGKZUQ2G7rkY1hQdkQqWzE',
    appId: '1:173490396619:ios:7080c1789185b413c7aa4e',
    messagingSenderId: '173490396619',
    projectId: 'kerala-psc-papers',
    databaseURL: 'https://kerala-psc-papers.firebaseio.com',
    storageBucket: 'kerala-psc-papers.appspot.com',
    iosBundleId: 'com.example.licenceApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB7ryYTN0QB3DBxLRkO4WcgyZ5l8qiYaKM',
    appId: '1:173490396619:web:6f3dafcc0a049f26c7aa4e',
    messagingSenderId: '173490396619',
    projectId: 'kerala-psc-papers',
    authDomain: 'kerala-psc-papers.firebaseapp.com',
    databaseURL: 'https://kerala-psc-papers.firebaseio.com',
    storageBucket: 'kerala-psc-papers.appspot.com',
    measurementId: 'G-5L6170DWHS',
  );

}